# Generated by Django 3.2.7 on 2021-11-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='date_of_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
