# Generated by Django 3.2.7 on 2021-11-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todotask_date_of_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotask',
            old_name='date_of_complete',
            new_name='date_of_completed',
        ),
    ]
